# These Blocks ignore all rules when placed in build mode
buildmode-blocks:
  - BROWN_MUSHROOM
  - RED_MUSHROOM
  - WARPED_FUNGUS
  - CRIMSON_FUNGUS
  - CRIMSON_ROOTS
  - WARPED_ROOTS
  - FERN
  - SUGAR_CANE
  - DEAD_BUSH
  - AZALEA
  - FLOWERING_AZALEA
  - DANDELION
  - POPPY
  - BLUE_ORCHID
  - ALLIUM
  - AZURE_BLUET
  - RED_TULIP
  - ORANGE_TULIP
  - WHITE_TULIP
  - PINK_TULIP
  - OXEYE_DAISY
  - CORNFLOWER
  - LILY_OF_THE_VALLEY
  - WITHER_ROSE
  - SPRUCE_SAPLING
  - ACACIA_SAPLING
  - BIRCH_SAPLING
  - OAK_SAPLING
  - DARK_OAK_SAPLING
  - JUNGLE_SAPLING
  - CACTUS
  - ROSE_BUSH
  - LILAC
  - SUNFLOWER
  - MANGROVE_PROPAGULE